version: '3.3'
services:
  alabuga-service-postgres:
    container_name: alabuga-service-postgres
    image: postgres:12.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - './dump:/var/lib/postgresql/data'
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}

